spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    generate-ddl: true

route:
  api: api
  book:
    path: book
  category:
    path: category
    children: children
  recipe:
    path: recipe
